# Site settings
title: Sattish Shewkani
description: A page about me.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sattish Shewkani
user_description: I\'m a 16 year old programmer, and I like to work with JS & Nodejs. You can check out my Github Page here <a href="https://github.com/Sattishh" target="_blank">https://github.com/Sattishh</a>
user_title: Aspiring Computer Programmer
email: spshewkani@gmail.com
# twitter_username: lorem_ipsum
# github_username:  Sattishh
# gplus_username:  lorem_ipsum

# Google-analytics
#google-analytics:
#  id: ""

exclude: ['package.json', 'src' , 'node_modules']
